### ISSUE TITLE
Create WAV files that do not write disk?

### ISSUE THREAD

**Issue by Vulpovile** [datajerk/c2t#13]
I have no disk drive, only the cassette port. I wanted to play some games from my computer, but can't find any working disk images.

**Comment by datajerk** [comment]
Disk-based games mostly require a disk, usually because the game cannot fit into RAM and/or to save state.  c2t just creates a wav of a disk image to then autoexpand to a system with a disk (e.g. https://asciiexpress.net/diskserver/)

However there are some games that will fit in RAM and that do not save state and c2t can create wavs of those as well (see the README.md), or you can access all that I am aware of here: https://asciiexpress.net/gameserver/

**Comment by Vulpovile** [comment]
Wow what a complete brain fart I had! I should have realized there was no way of putting >32K disks into 32K of RAM. Thanks!
